steps:
- bash: |
    terraform plan \
      -var superadmins_aad_object_id=$(kv-aad-superadmins-group-id) \
      -var 'application_owners_ids=$(kv-aad-app-owners-ids)' \
      -var-file=$(terraformVarFile) \
      -out $(terraformPlanFile)
  displayName: Terraform Plan
  env:
    ARM_SUBSCRIPTION_ID:        $(kv-arm-subscription-id)
    ARM_CLIENT_ID:              $(kv-arm-client-id)
    ARM_CLIENT_SECRET:          $(kv-arm-client-secret)
    ARM_TENANT_ID:              $(kv-arm-tenant-id)
    AZDO_ORG_SERVICE_URL:       $(devopsOrgUrl)
    AZDO_PERSONAL_ACCESS_TOKEN: $(kv-ado-pat)
