steps:
- bash: |
    terraform -auto-approve $(tf-plan-file)
  displayName: Terraform Apply
  env:
    ARM_SUBSCRIPTION_ID:        $(kv-arm-subscription-id)
    ARM_CLIENT_ID:              $(kv-arm-client-id)
    ARM_CLIENT_SECRET:          $(kv-arm-client-secret)
    ARM_TENANT_ID:              $(kv-arm-tenant-id)
    AZDO_ORG_SERVICE_URL:       $(kv-ado-dev-org-url) # TODO: Dev Org
    AZDO_PERSONAL_ACCESS_TOKEN: $(kv-ado-pat)
