steps:
- bash: |
    terraform apply -auto-approve $(terraformPlanFile)
  displayName: Terraform Apply
  env:
    ARM_SUBSCRIPTION_ID:        $(kv-arm-subscription-id)
    ARM_CLIENT_ID:              $(kv-arm-client-id)
    ARM_CLIENT_SECRET:          $(kv-arm-client-secret)
    ARM_TENANT_ID:              $(kv-arm-tenant-id)
    AZDO_ORG_SERVICE_URL:       $(devopsOrgUrl)
    AZDO_PERSONAL_ACCESS_TOKEN: $(kv-ado-pat)
