name: $(BuildID)

trigger:
  branches:
    include:
    - feat/*
    - fix/*
  paths:
    exclude:
    - '.github/*'
    - 'backends/*'
    - 'modules/cicd-setup'
    - 'images/*'
    - '*.md'
pool:
  vmImage: 'ubuntu-latest'

stages:
- template: ./stages/ci.yaml
