name: $(BuildID)

pool:
  vmImage: 'ubuntu-18.04'

trigger: none # PR only

pr:
- main

variables:
  - template: vars/global.yaml
  - group: e2e-gov-demo-dev-kv # DEV
  - group: mask-ids

stages:
  - template: stages/ci.yaml
  - template: stages/pull-request.yaml
